<?php

namespace Book\BookBundle\Repository;

/**
 * BorrowersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowersRepository extends \Doctrine\ORM\EntityRepository
{
}
