users_users:
    resource: "@UsersUsersBundle/Controller/"
    type:     annotation
    prefix:   /

book_book:
    resource: "@BookBookBundle/Controller/"
    type:     annotation
    prefix:   /book

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"